### ISSUE TITLE
 nvida (nvcr.io) pull doesn't work

### ISSUE THREAD

**Issue by rathamahata** [singularityhub/sregistry-cli#118]
(root) -bash-4.1$ ./bin/sregistry version
0.0.64
(root) -bash-4.1$ env | grep NVIDIA
SREGISTRY_NVIDIA_TOKEN=xxxxxxxxxxxxxxxxxxx
(root) -bash-4.1$  MESSAGELEVEL=6 SREGISTRY_CLIENT=nvidia ./bin/sregistry pull tensorflow:18.04-py3DEBUG credentials cache
DEBUG Headers found: Accept,Content-Type,Authorization
DEBUG Database located at sqlite:////user/e154466/.singularity/sregistry.db
DEBUG credentials cache
DEBUG Headers found: Accept,Content-Type,Authorization
DEBUG Database located at sqlite:////user/e154466/.singularity/sregistry.db
[client|nvidia] [database|sqlite:////user/e154466/.singularity/sregistry.db]
DEBUG Execution of PULL for 1 images
VERBOSE Obtaining manifest: https://nvcr.io/v2/nvidia/tensorflow/manifests/18.04-py3
DEBUG GET https://nvcr.io/v2/nvidia/tensorflow/manifests/18.04-py3
ERROR Unrecognized authentication challenge, exiting.
(root) -bash-4.1$

**Comment by vsoch** [comment]
hey I just removed your token - be careful about that! I'll get this checked out for you this weekend.

**Comment by vsoch** [comment]
Any updates here @rathamahata ? I was not able to pull with the token you have previously provided (and I hope you have since revoked since you posted here!)

**Comment by rathamahata** [comment]
Sorry for delay 0.0.84 works for me!

I found also that latest and greatest sigularity version works for me just fine (as per https://github.com/singularityware/singularity/issues/1159)

Thanks!
