### ISSUE TITLE
Missing dependencies in Singularity recipe file

### ISSUE THREAD

**Issue by samcmill** [singularityhub/sregistry-cli#121]
Building the Singularity container image does not result in a working container.  The build of Singularity fails due to missing dependencies.

```
$ sudo /usr/local/bin/singularity build sregistry-cli Singularity
... 
+ ./configure --prefix=/usr/local
...
checking for python... no
configure: error: Please install python before installing.
...
checking archive.h usability... no
checking archive.h presence... no
checking for archive.h... no
configure: error: Unable to find the libarchive headers, need package libarchive-devel (libarchive-dev on Debian/Ubuntu)
```

This results in a non-working container:

```
$ ./sregistry-cli pull ...
WARNING Singularity is not installed, function might be limited.
WARNING Singularity is not installed, function might be limited.
...
ERROR Cannot find Singularity! Is it installed?
```

I was able to work around the issue by adding `python` and `libarchive-dev` to the list of packages installed by `apt-get`.

**Comment by vsoch** [comment]
hey @samcmill ! Yes we definitely need to upgrade to account for the new Singularity dependencies. The Python install in the container (at /opt/conda) also can just be added to the path. I am working on this now - the Docker example needs updating as well. Stay tuned!

**Comment by vsoch** [comment]
Alrightly! When you are able, could you give this a test?

https://github.com/singularityhub/sregistry-cli/pull/122
