### ISSUE TITLE
broken image download with distant networks

### ISSUE THREAD

**Issue by ncde** [singularityhub/sregistry-cli#124]
the command 
sudo singularity pull shub://sregistry.srv.cesga.es/mso4sc/fenics-unicorn:latest

stops around 93% when I try it on another machine than Finis Terrae 2, for example
KTH tegner or my own laptop. 
the image downloaded this way also doesn't function. 

This might be due to strict threshold in timeout value. It is rather important for us to use in the KTH  Mooc course, can you check please?

**Comment by vsoch** [comment]
hey @ncde apologies that I missed this! The download looks like it's using singularity natively, so it would be more appropriate to post on those boards. Thanks!
