### ISSUE TITLE
[Return status 413 Request Entity Too Large]

### ISSUE THREAD

**Issue by Trophime** [singularityhub/sregistry-cli#126]
Hi, trying to push an image to an private collection in sregstry I end up with the following message:
```
singularity run sregistry-latest.simg  push --tag 10.2.3c --name hifimagnet/ensight ~/feelpp/research/hifimagnet/singularity/ensight/ensight-10.2.3c.simg
[client|registry] [database|sqlite:////home/LNCMI-G/trophime/.singularity/sregistry.db]
[================================] 1144/1144 MB - 00:00:00
[Return status 413 Request Entity Too Large]
```
what's wrong?

**Comment by vsoch** [comment]
Do you get a different response with a public collection?

**Comment by Trophime** [comment]
same issue.
It's working with images of smaller size

**Comment by vsoch** [comment]
Ah ok, this isn't a new issue, it's related to needing chunked upload for sregistry --> https://github.com/singularityhub/sregistry/issues/109 I'm going to close the issue here because the client already is ready to do this, and the work is needed for the server.

**Comment by Trophime** [comment]
it works with images of smaller size
