### ISSUE TITLE
How to push to remote sregistry

### ISSUE THREAD

**Issue by ttekampe** [singularityhub/sregistry-cli#128]
Hi,

I have an sregistry server running and am now trying to push to it from my laptop.
So on my laptop I added the token I got from the web-interface of the sregistry server to `~/.sregistry` and set the environment variable `export SREGISTRY_CLIENT="registry"` but when I run the push command, the image is always added to a local data base and not to the sregistry server.

```
ttekampe@tobi-laptop ~ % cat ~/.sregistry
{ "registry": { "token": "...my secret token...", "username": "ttekampe", "base": "http://... the url to my server...." } }
ttekampe@tobi-laptop ~ % echo $SREGISTRY_CLIENT
registry
ttekampe@tobi-laptop ~ % sregistry push root_ml.simg --name analysis/root_ml --tag 0.1
[client|registry] [database|sqlite:////home/ttekampe/.singularity/sregistry.db]
```

The `~/.sregistry` file seems to be seen by the sregistry client, because:

```
ttekampe@tobi-laptop ~ % sregistry backend ls registry
registry
{
    "base": "http://... the url to my server....",
    "token": "...my secret token...",
    "username": "ttekampe"
}
```

I tried with 

```
sregistry backend activate registry
```
but I am still pushing to this local data base.

What am I doing wrong?

**Comment by vsoch** [comment]
okay that looks right, so let's do a bit of debugging. When you do 

```
docker-compose logs uwsgi
docker-compose logs nginx
```
Do you see a record of the attempted push (with some error message) or is it completely absent?

**Comment by vsoch** [comment]
And note you should do this from the singularity registry root folder (where it is served from and the docker-compose.yml is)

**Comment by mbieker** [comment]
Hi I set up the sregistry together with @ttekampe at our institute. I took a look at the logs of the sregistry containers:

For the nginx container
`<10.42.178.230 > - - [02/Jul/2018:07:52:29 +0000] "GET /api/push/ HTTP/1.1" 200 52 "-" "python-requests/2.19.1" "<client-ip>"`
For the uwsgi container
`[pid: 92|app: 0|req: 79/79] 10.42.178.230 () {42 vars in 691 bytes} [Mon Jul  2 09:52:29 2018] GET /api/push/ => generated 52 bytes in 7 msecs (HTTP/1.1 200) 5 headers in 155 bytes (1 switches on core 0`

Cheers,

Martin.

**Comment by vsoch** [comment]
Hmm, at first glance it's off that nginx is reporting a GET when it's a POST that is done. Did you do any customization / tweaking of the nginx.conf files? Something like this comes to mind --> https://serverfault.com/questions/434205/nginx-https-rewrite-turns-post-to-get

At this point we have two options - given that we are reviewing a big PR for the pushing of containers (so it's done with nginx uploads)  this changes the client and server quite a bit, so you might be better off reviewing that work (and then deploying that updated sregistry / sregistry-cli) --> https://github.com/singularityhub/sregistry/pull/134

In the case that you want to use this version, know that you will have issue with large containers (what the PR above fixes) and to debug we would need to look at why the POST is not going through as expected, likely with careful walkthrough of these actions --> https://github.com/singularityhub/sregistry-cli/blob/master/sregistry/main/registry/push.py and inspection of headers along the way. 

Let me know your thoughts!

**Comment by mbieker** [comment]
I just found the solution to our issue. When we changed to SSL I forgot to update the DOMAIN_NAME in settings.py to https:// 🙈 . So fixing the URL in the token fixes the problem. So we'll fist go with the default version. If we encounter any issues with larger images we'll let you know. Thank you for your help!

**Comment by vsoch** [comment]
Woohoo! Great to hear. Closing issue!
