### ISSUE TITLE
NameError: global name 'cli' is not defined

### ISSUE THREAD

**Issue by AldoCP** [singularityhub/sregistry-cli#130]
Re sregistry-cli/docs/clients/debug/docker.md

When I run 

`SREGISTRY_CLIENT=docker sregistry shell`

I get the following output: 

> [client|docker] [database|sqlite:////home/users/aldocp/.singularity/sregistry.db]
> [client|docker] [database|sqlite:////home/users/aldocp/.singularity/sregistry.db]
> Traceback (most recent call last):
>   File "/scratch/users/aldocp/deepvar/project03/bin/sregistry", line 11, in <module>
>     sys.exit(main())
>   File "/scratch/users/aldocp/deepvar/project03/lib/python2.7/site-packages/sregistry/client/__init__.py", line 380, in main
>     subparser=subparsers[args.command])
>   File "/scratch/users/aldocp/deepvar/project03/lib/python2.7/site-packages/sregistry/client/shell.py", line 53, in main
>     return lookup[shell](args)
>   File "/scratch/users/aldocp/deepvar/project03/lib/python2.7/site-packages/sregistry/client/shell.py", line 86, in python
>     code.interact(local={"client":cli,
> NameError: global name 'cli' is not defined

Should I set the "cli" variable as well?

**Comment by vsoch** [comment]
No this looks like a bug, what version are you running?

```
sregistry version
```

**Comment by vsoch** [comment]
okay please see https://github.com/singularityhub/sregistry-cli/pull/131 I think that should resolve the issue! Let me know when it looks good and I'll merge and update on pypi.

And thanks for this catch! I always use ipython so I didn't get to the vanilla python shell!
