### ISSUE TITLE
Can't get manifest

### ISSUE THREAD

**Issue by AldoCP** [singularityhub/sregistry-cli#132]
Re sregistry-cli/docs/clients/debug/docker.md

A couple of (probably minor) issues/pull requests: 

1) The os library needs to be imported: 
`import os`
`file_name = os.path.basename(q['storage'])`

2) Probably a typo here: 
`digest = names['version'] or names['tag']`, 
which gives: 
> Traceback (most recent call last):
>   File "<console>", line 1, in <module>
> TypeError: 'module' object has no attribute '__getitem__'

Did you mean `digest = q['version'] or q['tag']`? 

Apart from that, the output is ok (v2 manifest is the only one that works). Looking forward to the v1-compatible version; thanks!

**Comment by vsoch** [comment]
hey @AldoCP I just pushed fixes for this! I couldn't find where you are referencing the first line about storage, can you show me? For the second (names) that was a typo (names is used in the original script). For your last comment, the registry is never going to serve a version 1 manifest, so unfortunately you don't have that to look forward to. 

Take a look here --> https://cloud.google.com/container-registry/docs/image-formats gcr.io only serves version 2 flavors.

Let me know if it looks ok now!

**Comment by vsoch** [comment]
I believe this is fixed, closing. Please re-open if there is still an issue, thanks!
