### ISSUE TITLE
unable to upload image to registry instance (Max retries exceeded with url: /upload)

### ISSUE THREAD

**Issue by hv15** [singularityhub/sregistry-cli#137]
Hi,

I recently setup a registry on my local network and have been trying to upload some images to one of the collections. The images a very large (between 5 and 10 GB). I've generated my token from the registry and have added this to the `~/.sregistry` file.

I do the following:
```
$ export SREGISTRY_CLIENT=registry
$ sregistry push --name test/test --tag 1 ~/test.simg
```
and get this error:
```
[client|registry] [database|sqlite:////home/user/.singularity/sregistry.db]

[1. Collection return status 200 OK]
HTTPSConnectionPool(host='<some url>', port=443): Max retries exceeded with url: /upload (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7e436350b8>: Failed to establish a new connection: [Errno -2] Name or service not known'))
```

The log output from the registry nginx instances is:
```
nginx_1   | 192.168.88.254 - - [15/Aug/2018:11:13:19 +0000] "POST /api/upload/chunked_upload HTTP/1.1" 200 10 "-" "python-requests/2.19.1" "<some remote ip>"
```
and the uwsgi log output is:
```
uwsgi_1   | [pid: 83|app: 0|req: 52/52] 192.168.88.254 () {46 vars in 769 bytes} [Wed Aug 15 06:13:19 2018] POST /api/upload/chunked_upload => generated 10 bytes in 7 msecs (HTTP/1.1 200) 3 headers in 100 bytes (1 switches on core 0)
```

One aspect of my configuration that _could_ be causing problems is that the whole registry setup is running behind a haproxy service (through which I also host the site as HTTPS).

Thanks,
Hans

**Comment by vsoch** [comment]
Yes I think it's definitely the proxy - the setup would be sensitive to this. Based on the output I don't think it's an issue with the client, but the configuration for your registry (the example and testing I did does not involve a proxy). Here is the issue boards for the registry (and not the client) --> https://github.com/singularityhub/sregistry/issues if it helps!

I'm not sure how to debug or help here, I think one of our users had a similar setup and got it working? Take a look at the original issue, https://github.com/singularityhub/sregistry/issues/123 and pinging @jpunzel and @fearful-symmetry.

**Comment by hv15** [comment]
@vsoch thanks for the reply. As it turns out, it has nothing to do with the Haproxy setup. Instead there is a bug in `push.py` of the registry backend. At one point we do
```
url = '%s/upload' % self.base.strip('api/')
```
If the `self.base` has *any* of the characters `'api/'`, the URL is corrupted. E.g. `'ah.blah.ninja'.strip('api/')` returns `'h.blah.ninj'`. I've fixed this now by using `.replace('/api','')` instead and the `push` looks to be working correctly now. I'll do a PR soon, I'd like to do more testing first.

**Comment by vsoch** [comment]
Oh great! I've run into this error before, never quite understood it. When you are happy with the changes, would you care to do a PR so it doesn't mess up anyone else?
