### ISSUE TITLE
`rename` behavior change from 0.0.74 to 0.0.94?

### ISSUE THREAD

**Issue by Trophime** [singularityhub/sregistry-cli#154]
Hi, I'm facing some issues with the change of behavior of `rename` from 0.0.74:
````
[rename] hifimagnet-salome:8.3.0.simg => $SREGISTRY_STORAGE/salome-8.3.0.simg
````
to 0.0.94:
```
[rename] hifimagnet-salome:8.3.0.simg => $SREGISTRY_STORAGE/library/salome-8.3.0:latest.simg
```

Now, the renamed images are moved into a subdirectory `library`.
Next, the colon in the filename may become problematic as this character must be escaped in some shells... That's an issue for my scripts at least.

Is this change "permanent"? (maybe I missed something in the changelogs)
Could we replace the semicolon, at least when "renaming" the image with some more common character?

Best
C

**Comment by vsoch** [comment]
Definitely can be changed! I was trying to follow whatever would be considered "singularity convention" - do you want to look into this and let me know? I think you are right that the semicolon should be a `-`, and I'm glad to change it.

**Comment by Trophime** [comment]
Great. Thanks

Still, I have a couple of questions:
* what is the rationale behind moving renamed images to SREGISTRY_STORAGE/library?
* why not simply keep the name provided by the `rename` option instead of adding `:latest`.

**Comment by vsoch** [comment]
> what is the rationale behind moving renamed images to SREGISTRY_STORAGE/library?

primarily just organization of things, and avoiding having a huge number of files in one folder. By collection makes sense, and it was more of a bug that it wasn't done the first time.

> why not simply keep the name provided by the rename option instead of adding :latest.

If the use doesn't specify a name, it makes sense to include the tag, given that it's an important attribute.

> By the way what is the relation between sregistry and the "syslabs cloud" stuff?

There is none. Singularity Registry Server is an open source Singularity Hub, which is for academic use. It's important that an academic institution can always deploy their our registry. "Sylabs cloud stuff" I doubt would be released open source, and they are hoping to charge people for it. I don't know details beyond that.

Speaking of sregistry, I've been thinking of adding a builders plugin so an institution that deploys it could do the same as Singularity Hub (add recipe to Github, then have it build on Google Cloud). Does this sound interesting to you? I haven't heard any feedback from the community so I haven't done it yet, but intuitively I think it's important / needed.

**Comment by vsoch** [comment]
okay looks like we have a `-`

```bash
$ singularity pull shub://vsoch/hello-world
Progress |===================================| 100.0% 
Done. Container is at: /home/vanessa/vsoch-hello-world-master-latest.simg
```
I'll put in a PR to do this change.

**Comment by Trophime** [comment]
ok great 👍 
As for your proposal to have a builder plugin maybe we can start with travis or whatever ci system.
Another nice feature would be to have this singularity-clair security scanner.

Having access to cloud infrastructure (not necessarily Google Cloud, for instance, I doubt that my lab will pay for access Google cloud) to make the build would also be fine.

**Comment by vsoch** [comment]
My thinking was that if you can push, you can roll your own (whatever) and it should allow most institutions to have their own development workflow. This would be very easy to set up for Travis or Circle, so maybe as a next step I can write a how to guide (for you to test out) to deploy images from there? 

Another question! Clair is usually run as an instance, so would you want to put load on the same sregistry server, or have a one time (at time of build) sort of deal?

**Comment by vsoch** [comment]
Oh, and look like I already did this --> https://github.com/singularityhub/singularity-ci/ (but for travis)

**Comment by vsoch** [comment]
hey @Trophime ! I updated the travis example for you! https://github.com/singularityhub/travis-ci

Also, I revisited CircleCI, and remembered the reason it doesn't work is because they don't let you virtualize the mount namespace. I pinged them to see if there is a way around this. I'm going to give a try at the Github (newly announced) native CI, and wanted to ask you - are there Github integrated CI others (other than these two) that you would like me to test / setup?

**Comment by Trophime** [comment]
Thanks.
As for other CI, maybe Gitlab CI is also to consider is possible.
Maybe my colleagues @victorsndvg @prudhomm have some more insights on that

**Comment by vsoch** [comment]
okey doke.

Also, got circle-ci working! --> https://github.com/singularityhub/circle-ci

**Comment by vsoch** [comment]
It looks like this issue was resolved (rename), closing issue.
