### ISSUE TITLE
add way for client to push to sregistry with custom storage

### ISSUE THREAD

**Issue by vsoch** [singularityhub/sregistry-cli#174]
It should be possible for a user to use any of the clients (google-storage, etc.) but then use sregistry server as the database for users to interact with. There are a few options:

 - use the registry:// endpoint to push, and then when the file is uploaded via nginx upload, instead of saving to a permanent spot on the server, upload it to cloud storage. This is inefficient because it relies on the sregistry server to upload and then again push to another endpoint, but it makes sense if you have many users that want to push containers (and you wouldn't want to expose your specific storage credentials to them.)

@fenz what are your thoughts here? I don't see a way to have the push happen from the user because then if you had many users, you would need to share the endpoint credential (versus storing it on the sregistry server for them to take advance of).

Let me know your thoughts! I will pause on development until we've thought of a good solution. Arguably, the way sregistry is now (uploading via nginx upload module) isn't so far a cry from then pushing to another storage, but it still doesn't scale super well. But then again, how many pushes are likely to happen at once?

**Comment by vsoch** [comment]
yes I agree, but you didn't answer any of my questions. I was asking about the efficiency / logic of having the push to the server, then additionally to the storage, and if there are any other options to improve upon that.

**Comment by fenz** [comment]
I got it now. At the moment I can't think about anything different. 
Anyway, do you think this is much worst than having multiple users asking for writing on the FS? You can already mount these volumes anywhere, NFS or using any other docker storage driver, and having the same issue because the FS write will be translated by the storage driver to a different request. So I don't think having this second request to push to another storage is really bad.
I don't know how it exactly works when you send a push request to the sregistry (I'm not expert) but would it be possible to create a direct connection to the cloud storage when you ask for pushing an image? I don't want to write any (other) stupid thing so I'll try to dig into it and think a bit more about a possible alternative.

**Comment by fenz** [comment]
@vsoch  I have no idea about its implementation but the docker registry has actually the same: https://docs.docker.com/registry/configuration/ , in the config.yml file there's a "storage" section with: filesystem, azure, gcs, s3, swift, oss, inmemory and this is an example on how to use Minio for docker registry storage: https://medium.com/@enne/use-minio-as-docker-registry-storage-driver-c9c72c72cc87. 
Do you know how it works for docker registry? It would be nice to have the same level of customization for the storage in the sregistry.

**Comment by michaelmoore10** [comment]
@vsoch This is the model we are looking at for our registry at Nuance.  Our clusters cannot download the container images fast enough from the local file system storage on the sregistry server.

**Comment by vsoch** [comment]
Yes, I hear you both! I paused working on this because I'm exploring the idea of a static container registry (see my [original post](https://groups.google.com/a/opencontainers.org/d/msg/dev/RfOXu_8NA8k/Qc3CqEtoDQAJ) and the start of [discussion here](https://groups.google.com/a/opencontainers.org/forum/#!topic/dev/AR0mRIzmgzs)). I want to make it easier for (smaller institutions) to have a "plug and play" registry sort of setup, using something like Github Pages to serve the static API, connected to a storage of choice, and without the crazy needs to host a server just for the API. The links above are relevant to fitting that model into the OCI spec (a harder, longer discussion) but it would be much more quick and easy to have a static API serving an object store (like Minio, Google Storage) via building from GitHub. This would mean that you wouldn't push directly, but would go through standard pull request -> build in continuous integration to push to a registry.

That said, I have a lot of thinking to do about it, and for your purposes it makes more sense to keep working on this for sregistry server. But I wanted to share the idea with you because I think (not having to deploy a server for the API and still using storage) would be a very powerful model for many.

**Comment by vsoch** [comment]
Whoa @michaelmoore10 Nuance like, the company that makes voice recognition software? Do you make software that helps doctor's transcribe? I seem to remember my Dad telling me something about Dragon that he was dictating to (he's an ER doc on the East Coat). That would be so cool if that was your software... what a small world!

And he's completely computer illiterate so you must be doing a good job if he could use it, haha.

**Comment by vsoch** [comment]
@fenz and @michaelmoore10 do either of your use cases map to being able to / wanting to use a static registry? I've started development (write up for basic here -> https://vsoch.github.io/2019/static-registry/) and if it really is the case that you just need an API and interface to storage, this is a *much* more affordable option, and I'd like to offer to help develop this first. The static registry is ideal because it's flexible to using whatever build / storage strategy you like, and the recipes are version controlled / collaborated on easily via GitHub.

**Comment by vsoch** [comment]
This is done for Google Storage + Google Cloud Build. The client can interact with storage directly, or use Singularity Registry Server as an interface. For Singularity Registry Server I'd like to add some additional security checks.
