### ISSUE TITLE
Add Google Cloud Build

### ISSUE THREAD

**Issue by vsoch** [singularityhub/sregistry-cli#178]
Using the gcloud client is messy, might be worth trying interacting with the API directly,

**Comment by vsoch** [comment]
As discussed in work for https://github.com/wkharold/community/pull/3, we want to add integrations to users to take advantage of Google Build. Since gcloud had several issues on Circle CI, I think a cleaner approach will be to interact with just the Google Build / Google Storage APIs directly, and this can be done via the sregistry client. This is what I'll be trying here.

**Comment by vsoch** [comment]
hey @wkharold! I've started the integration for Google Cloud Build with the native sregistry client, and I've found the [API docs](https://cloud.google.com/cloud-build/docs/api/reference/rest/v1/projects.builds/create) for performing the actual build, but I can't seem to find the equivalent for a custom builder. Is this exposed, or will I need to either provide the builder somewhere for the user, or (still) rely on gcloud? Ideally, we could either:

 1. have a RESTful interaction with the custom build (to create the builder on the user's Google Cloud)
 2. have a Google provided Singularity builder (so the client doesn't need to do the custom build).

What are your thoughts? I was looking at the cloudbuild (via the discovery tool) and I'm just seeing the endpoints, to list, get, create, etc.

```
> dir(self._build_service.operations())
[...
 '_add_basic_methods',
 '_add_nested_resources',
 '_add_next_methods',
 '_baseUrl',
 '_developerKey',
 '_dynamic_attrs',
 '_http',
 '_model',
 '_requestBuilder',
 '_resourceDesc',
 '_rootDesc',
 '_schema',
 '_set_dynamic_attr',
 '_set_service_methods',
 'cancel',
 'get',
 'list',
 'list_next']

> dir(self._build_service.projects())
[...
 '_add_basic_methods',
 '_add_nested_resources',
 '_add_next_methods',
 '_baseUrl',
 '_developerKey',
 '_dynamic_attrs',
 '_http',
 '_model',
 '_requestBuilder',
 '_resourceDesc',
 '_rootDesc',
 '_schema',
 '_set_dynamic_attr',
 '_set_service_methods',
 'builds',
 'triggers']
```
where the self._build_service is generated via:

```python
from googleapiclient.discovery import build as discovery_build
self._build_service = discovery_build('cloudbuild', version, credentials=creds)
```
The goal is to easily have a custom build done and then sent to storage directly from CircleCI and similar. I had enough trouble with gcloud and conflict with the Circle environment that I'm trying this route instead. It will be much easier for the user to just issue a command to build, given a recipe, and not have to deal with all the various yaml configurations, etc.

**Comment by vsoch** [comment]
Okay I found [custom build steps](https://cloud.google.com/cloud-build/docs/build-config) with many json examples, but it looks like the Dockerfile can't be shoved into the json :) Looking more...

**Comment by vsoch** [comment]
Does the container to build have to be on Google Cloud? Can we use Docker Hub?

**Comment by wkharold** [comment]
It may be possible to get the container from Docker Hub but you would have to figure out how to do the necessary auth. I'll look into it.

**Comment by vsoch** [comment]
Ah! It seems to work (mostly) off the bat (using a public image that doesn't need auth):

```bash
$ gcloud builds submit --config=cloudbuild2.yaml --substitutions=_SINGULARITY_VERSION="3.0" .
Creating temporary tarball archive of 10 file(s) totalling 173.7 MiB before compression.
Uploading tarball of [.] to [gs://singularity-static-registry_cloudbuild/source/1550069779.47-ba2c44607332409fa7c31a2f98299994.tgz]
Created [https://cloudbuild.googleapis.com/v1/projects/singularity-static-registry/builds/90e8b0e7-fad2-46fe-97ac-c2b7737202f4].
Logs are available at [https://console.cloud.google.com/gcr/builds/90e8b0e7-fad2-46fe-97ac-c2b7737202f4?project=287055059824].
----------------------------------------------------- REMOTE BUILD OUTPUT -----------------------------------------------------
starting build "90e8b0e7-fad2-46fe-97ac-c2b7737202f4"

FETCHSOURCE
Fetching storage object: gs://singularity-static-registry_cloudbuild/source/1550069779.47-ba2c44607332409fa7c31a2f98299994.tgz#1550069794881224
Copying gs://singularity-static-registry_cloudbuild/source/1550069779.47-ba2c44607332409fa7c31a2f98299994.tgz#1550069794881224...
| [1 files][170.4 MiB/170.4 MiB]                                                
Operation completed over 1 objects/170.4 MiB.                                    
BUILD
Pulling image: singularityware/singularity:3.0
3.0: Pulling from singularityware/singularity
ff3a5c916c92: Pulling fs layer
1a649ea86bca: Pulling fs layer
ce35f4d5f86a: Pulling fs layer
7db6b75ae47d: Pulling fs layer
fc46bec5ec29: Pulling fs layer
50c1b2e23316: Pulling fs layer
ef5c66b9870b: Pulling fs layer
c48a8d21a99e: Pulling fs layer
752b5318d162: Pulling fs layer
15201efb35d4: Pulling fs layer
32694a734dd5: Pulling fs layer
7db6b75ae47d: Waiting
fc46bec5ec29: Waiting
50c1b2e23316: Waiting
ef5c66b9870b: Waiting
c48a8d21a99e: Waiting
752b5318d162: Waiting
15201efb35d4: Waiting
32694a734dd5: Waiting
ce35f4d5f86a: Verifying Checksum
ce35f4d5f86a: Download complete
1a649ea86bca: Verifying Checksum
1a649ea86bca: Download complete
ff3a5c916c92: Verifying Checksum
ff3a5c916c92: Download complete
ff3a5c916c92: Pull complete
fc46bec5ec29: Verifying Checksum
fc46bec5ec29: Download complete
1a649ea86bca: Pull complete
50c1b2e23316: Verifying Checksum
50c1b2e23316: Download complete
ce35f4d5f86a: Pull complete
ef5c66b9870b: Verifying Checksum
ef5c66b9870b: Download complete
7db6b75ae47d: Verifying Checksum
7db6b75ae47d: Download complete
c48a8d21a99e: Verifying Checksum
c48a8d21a99e: Download complete
752b5318d162: Verifying Checksum
752b5318d162: Download complete
32694a734dd5: Verifying Checksum
32694a734dd5: Download complete
15201efb35d4: Verifying Checksum
15201efb35d4: Download complete
7db6b75ae47d: Pull complete
fc46bec5ec29: Pull complete
50c1b2e23316: Pull complete
ef5c66b9870b: Pull complete
c48a8d21a99e: Pull complete
752b5318d162: Pull complete
15201efb35d4: Pull complete
32694a734dd5: Pull complete
Digest: sha256:11f21557e52b66b3bb85b87f26811cd5bc3a57795479eb06c399213511338f08
Status: Downloaded newer image for singularityware/singularity:3.0
WARNING: Authentication token file not found : Only pulls of public images will succeed
FATAL:   Error parsing input: EOF
ERROR
ERROR: build step 0 "singularityware/singularity:3.0" failed: exit status 255
Build target already exists. Do you want to overwrite? [N/y] 
-------------------------------------------------------------------------------------------------------------------------------

ERROR: (gcloud.builds.submit) build 90e8b0e7-fad2-46fe-97ac-c2b7737202f4 completed with status "FAILURE"
```

The cloudbuild2.yaml file:

```
steps:
- name: singularityware/singularity:${_SINGULARITY_VERSION}
  args: ['build', 'julia-centos.sif', 'julia.def']
artifacts:
  objects:
    location: 'gs://${PROJECT_ID}-singularity'
    paths: ['julia-centos.sif']
```
and the julia definition is the same. I'm trying to figure out which file it is having trouble parsing.

**Comment by vsoch** [comment]
Ah! This was a misleading error message. The reason it wasn't building wasn't because of parsing an EOF, but because there already was an image there (the line below it). When I renamed the image, the entire thing built and cleaned up nicely! It didn't complete the run because I didn't make the bucket, but I have pretty good confidence it would have gone there :)

So the end of the day message is that we don't actually need the custom build step, and this is really good news for sregistry client because that custom build step doesn't seem to have an API interaction yet. It's also nice because I don't have to "double build" my base images to build - I can use Docker Hub.

**Comment by vsoch** [comment]
Anyway TLDR we are good @wkharold because I can use the create (builder) API without needing the custom step. Thanks for your help!

**Comment by vsoch** [comment]
@wkharold one concern that I have is that with each build, this bundle (.tar.gz) is uploaded to a bucket (of the same name with `_cloudbuild` appended):

![image](https://user-images.githubusercontent.com/814322/52732183-90ef3200-2f8d-11e9-879a-527890ebd1ec.png)

The user is largely not notified or aware of this bucket creation and storing, and it feels like a sneaky "oops you are paying for this storage and you didn't know it!" sort of deal. Can we have a --cleanup or --no-cache option to essentially remove the build dependencies after the container is uploaded to (a different) storage bucket? There really must be transparency in this interaction, because it might hurt the reputation of the tool to discover this after the fact. Let me know your thoughts! Is there a way to give feedback to the SWEs writing the tools?

**Comment by wkharold** [comment]
Awesome progress! I'll look into these "build droppings" to see (a) if there is potential for users to be charged for them, and (b) look into the --cleanup, --no-cache options.

**Comment by vsoch** [comment]
haha build droppings! I used to have small rodents growing up, and well, that's what comes to mind :)

At first I was thinking that I can just clean up after the build is done (the bucket is programatically predictable) but this breaks rather quickly for scaled builds to the same bucket. I'll leave as is for now.

**Comment by vsoch** [comment]
hey @wkharold ! Have you gotten any response back from your team about imaging naming? For example, I'm putting together a build configuration for the API, and need to specify a container to build under args:

```
args: ['build', 'julia-centos-another.sif', 'julia.def']
```

and then to send that some container to a (versioned) path in storage:

```
            location: 'gs://sregistry-gcloud-build-vanessa'
            paths: ['julia-centos-another.sif']
```

Ideally, we want the final container name to be something with the hash (e.g., `busybox-latest@31250aff0ac5972820b943077318d4c1.simg`) but this of course we cannot know until we build the container! It's a catch 22. What I'd want to do is perhaps create a custom builder that knows to build the image, and then rename based on the hash, and then export the name to an environment variable (or some similar strategy) that is then passed on to the build config. Something like:

```
        steps:
        - name: "singularityware/singularity:${_SINGULARITY_VERSION}"
          # The args would hit a different entrypoint than the Singularity executable, one that would build and rename based on the hash produced
          args: ['build', 'julia.def']
        artifacts:
          objects:
            location: 'gs://sregistry-gcloud-build-vanessa'
            # And then down here, we would get the final name from the environment...
            paths: ['${CONTAINER_NAME}']
           # or from a command? (think some parsing of env | grep CONTAINER_NAME...)
```

What do you think?

**Comment by vsoch** [comment]
For now I'm going to do "crappy misleading versioning" - meaning the container name and tag. It will hit a bump if/when the path already exists but I'll debug that when I hit it :)

**Comment by vsoch** [comment]
Actually here is says:

> Files in the workspace matching specified paths globs will be uploaded to the specified Cloud Storage location using the builder service account's credentials.

If "glob" is being used in the python sense, that could be a general *.sif (and this would allow for uploading any named container). I'm guessing this isn't the case and glob is referring to a file blob, but it's worth a try! If this does work, we would then need to programmatically get the latest built container name from storage to return to the user (if he / she wanted to retrieve it).

**Comment by vsoch** [comment]
Okay, test number 1 - here we have a config with a specific container name (I haven't built the container yet to rename based on hash) and the general "glob" instruction to upload any *.sif to storage:

```
{
    "steps": [
        {
            "name": "singularityware/singularity:3.0",
            "args": [
                "build",
                "dinosaur-container-latest.sif",
                "Singularity"
            ]
        }
    ],
    "artifacts": {
        "objects": {
            "location": "sregistry-gcloud-build-vanessa",
            "paths": [
                "*.sif"
            ]
        }
    }
}
```

## Bug 1: ProjectID is required

The documentation states that the projectID is "output only" (I inferred that it would return based on the discovery credential)

> string Output only. ID of the project.

But this isn't the case:

```
TypeError: Missing required parameter "projectId"
```

So I added it! But it turns out, it wants the variable given to the client, like this:

```
response = self._build_service.projects().builds().create(projectId=project,
                                                                                          body=config).execute()
```
which also kind of goes against my expectation, because for compute I did the same but just specified "project." No worries, I can do that! And hey, that was easier than I expected - not sure if this will work, but we have a queued build, woohoo!

```bash
{'metadata': {'@type': 'type.googleapis.com/google.devtools.cloudbuild.v1.BuildOperationMetadata',
  'build': {'artifacts': {'objects': {'location': 'gs://sregistry-gcloud-build-vanessa/',
     'paths': ['*.sif']}},
   'createTime': '2019-02-13T22:08:25.768630097Z',
   'id': 'ac23c2fe-0385-4957-a4aa-4c71065558c7',
   'logUrl': 'https://console.cloud.google.com/gcr/builds/ac23c2fe-0385-4957-a4aa-4c71065558c7?project=287055059824',
   'logsBucket': 'gs://287055059824.cloudbuild-logs.googleusercontent.com',
   'options': {'logging': 'LEGACY'},
   'projectId': 'singularity-static-registry',
   'status': 'QUEUED',
   'steps': [{'args': ['build',
      'dinosaur-container-latest.sif',
      'Singularity'],
     'name': 'singularityware/singularity:3.0'}],
   'timeout': '600s'}},
 'name': 'operations/build/singularity-static-registry/YWMyM2MyZmUtMDM4NS00OTU3LWE0YWEtNGM3MTA2NTU1OGM3'}
```
I'm sure it will fail on this first try, but still, it gives me immesurable pleasure when I sent a message to some cloudy API, and said cloudy API writes back :) I'll update the issue when I learn more.

**Comment by wkharold** [comment]
I'm not sure about the hash in the name. As you point out you can't know it a priori and it would be impossible to get right if you ever had to type it. You do want traceability back to the hash it was built from but it seems like that could live in metadata rather than being folded into the name. Personally I like semantic versioning even though it is often crappy and misleading.

**Comment by wkharold** [comment]
> Okay, test number 1 - here we have a config with a specific container name (I haven't built the container yet to rename based on hash) and the general "glob" instruction to upload any *.sif to storage:
> 
> ```
> {
>     "steps": [
>         {
>             "name": "singularityware/singularity:3.0",
>             "args": [
>                 "build",
>                 "dinosaur-container-latest.sif",
>                 "Singularity"
>             ]
>         }
>     ],
>     "artifacts": {
>         "objects": {
>             "location": "sregistry-gcloud-build-vanessa",
>             "paths": [
>                 "*.sif"
>             ]
>         }
>     }
> }
> ```
> ## Bug 1: ProjectID is required
> The documentation states that the projectID is "output only" (I inferred that it would return based on the discovery credential)
> 
> > string Output only. ID of the project.
> 
> But this isn't the case:
> 
> ```
> TypeError: Missing required parameter "projectId"
> ```
> So I added it! But it turns out, it wants the variable given to the client, like this:
> 
> ```
> response = self._build_service.projects().builds().create(projectId=project,
>                                                                                           body=config).execute()
> ```
> which also kind of goes against my expectation, because for compute I did the same but just specified "project." No worries, I can do that! And hey, that was easier than I expected - not sure if this will work, but we have a queued build, woohoo!
> 
> ```shell
> {'metadata': {'@type': 'type.googleapis.com/google.devtools.cloudbuild.v1.BuildOperationMetadata',
>   'build': {'artifacts': {'objects': {'location': 'gs://sregistry-gcloud-build-vanessa/',
>      'paths': ['*.sif']}},
>    'createTime': '2019-02-13T22:08:25.768630097Z',
>    'id': 'ac23c2fe-0385-4957-a4aa-4c71065558c7',
>    'logUrl': 'https://console.cloud.google.com/gcr/builds/ac23c2fe-0385-4957-a4aa-4c71065558c7?project=287055059824',
>    'logsBucket': 'gs://287055059824.cloudbuild-logs.googleusercontent.com',
>    'options': {'logging': 'LEGACY'},
>    'projectId': 'singularity-static-registry',
>    'status': 'QUEUED',
>    'steps': [{'args': ['build',
>       'dinosaur-container-latest.sif',
>       'Singularity'],
>      'name': 'singularityware/singularity:3.0'}],
>    'timeout': '600s'}},
>  'name': 'operations/build/singularity-static-registry/YWMyM2MyZmUtMDM4NS00OTU3LWE0YWEtNGM3MTA2NTU1OGM3'}
> ```
> 
> I'm sure it will fail on this first try, but still, it gives me immesurable pleasure when I sent a message to some cloudy API, and said cloudy API writes back :) I'll update the issue when I learn more.

Nice! I hate doc bugs! There might be a link on the page where they lie about the project id that you can use to complain via bug report.

You're killing it.

**Comment by vsoch** [comment]
Interesting, so the tar.gz bundle uploaded is done by gcloud builds and includes the build context, and given that I reproduce that I can get the exact path and remove it after. One note of concern - for gcloud builds, if there are any secrets files in the $PWD (build context) they would be uploaded.

**Comment by vsoch** [comment]
Woo!! I haven't pushed the code yet, but my builder just uploaded his .tar.gz context, and built a container :)

```
LOG build 35ce4404-68e1-47e2-8453-f88fdb169906: WORKING
LOG build 35ce4404-68e1-47e2-8453-f88fdb169906: WORKING
LOG build 35ce4404-68e1-47e2-8453-f88fdb169906: WORKING
LOG build 35ce4404-68e1-47e2-8453-f88fdb169906: WORKING
LOG build 35ce4404-68e1-47e2-8453-f88fdb169906: WORKING
LOG build 35ce4404-68e1-47e2-8453-f88fdb169906: WORKING
LOG build 35ce4404-68e1-47e2-8453-f88fdb169906: WORKING
LOG build 35ce4404-68e1-47e2-8453-f88fdb169906: SUCCESS
```
baby steps!

**Comment by vsoch** [comment]
Okay and here is the metadata I'm going to save with the built container - the names of the containers are given human friendly names (e.g., vanessa-dinosaur-latest.sif) but then the image hash and all the build details are stored with this metadata:

```
In [204]: metadata
Out[204]: 
{'artifactManifest': 'gs://sregistry-gcloud-build-vanessa/artifacts-35ce4404-68e1-47e2-8453-f88fdb169906.json',
 'buildCommand': 'build vanessa-avocados-latest.sif Singularity',
 'builder': 'singularityware/singularity:3.0',
 'file_hash': 'K1k1VTFxaTRuUDlrdVJHSEFMa1VhZz09',
 'location': 'gs://sregistry-gcloud-build-vanessa/vanessa-avocados-latest.sif#1550178633520351',
 'storageSourceBucket': 'sregistry-gcloud-build-vanessa_cloudbuild',
 'storageSourceObject': 'source/5f062e4ff01a4b72301027d637763aa79a6255342f0348e1869ee8ce6ff0ee68.tar.gz'}
```
I could also rename the container to be the hash, but then if the user is browsing it's totally useless. It's also hard to match the artifacts json object to containers, so that's why I'm adding the metadata directly to the image.

**Comment by wkharold** [comment]
Outstanding. These are some big "baby" steps!

**Comment by vsoch** [comment]
Yeah! I think it's all there, and maybe just one more session to clean up the code and write docs, record some asciinema, etc. Basically, it works as following:

 1. The user must export their application credentials and project id
 2. The command is generally `sregistry build <recipe> <context>`, and context can be undefined (just the recipe) or a list of files, or all files in the $PWD (`.`) Here are some examples:

```bash
export SREGISTRY_CLIENT=google-build
sregistry build Singularity
sregistry build Singularity file1 file2
sregistry build .
```

The above gives the user the most control over the build context and what gets uploaded. For the user, the build then happens, and after the (WORKING) commands above, the final result is printed to the screen:

```
SUCCESS gs://sregistry-gcloud-build-vanessa/vanessa-avocados-latest.sif
LOG https://www.googleapis.com/download/storage/v1/b/sregistry-gcloud-build-vanessa/o/vanessa-avocados-latest.sif?generation=1550178633520351&alt=media
LOG https://console.cloud.google.com/gcr/builds/35ce4404-68e1-47e2-8453-f88fdb169906?project=287055059824
```
But actually, it's a bit more than that! The client first creates a temporary directory, generates a .tar.gz with the context, and uploads to the same bucket (with _cloudbuild appended, like gcloud does). If the .tar.gz is found to already exists because the user export `SREGISTRY_GOOGLE_BUILD_CACHE`, then the upload is skipped. The [cloud builds create](https://cloud.google.com/cloud-build/docs/api/reference/rest/v1/projects.builds/create) endpoint is then used (via the discovery client) with a config that is basically the same as the yaml files we've worked with, but in json. It additionally has the path to the source repository with the build dependencies. Something like this:

```
{
    "artifacts": {
        "objects": {
            "location": "gs://sregistry-gcloud-build-vanessa",
            "paths": [
                "vanessa-avocados-latest.sif"
            ]
        }
    },
    "source": {
        "storageSource": {
            "bucket": "sregistry-gcloud-build-vanessa_cloudbuild",
            "object": "source/5f062e4ff01a4b72301027d637763aa79a6255342f0348e1869ee8ce6ff0ee68.tar.gz"
        }
    },
    "steps": [
        {
            "args": [
                "build",
                "vanessa-avocados-latest.sif",
                "Singularity"
            ],
            "name": "singularityware/singularity:3.0"
        }
    ]
}
```
Notice the name - that's the Docker Hub container [here](https://hub.docker.com/r/singularityware/singularity/tags) and I'm actually changing it to 3.0.2-slim since it's a much smaller container. The user can determine this version of Singularity with `SREGISTRY_GOOGLE_BUILD_SINGULARITY_VERSION`  (kind of long, I'm okay with it!). After the build completes, we again check the cache variable and if it's set by the user, we don't clean up the cloudbuild bucket (this means by default we don't save any extra files - we clean up!) Finally, the metadata from the artifacts json and config are saved with the object, and the user is shown the logs url, and the media link. If `SREGISTRY_GOOGLE_STORAGE_PRIVATE` is set in the environment, the container is not made public.

Anyhoo I'll write this up more cleanly and also clean up things a bit, and I'll update the PR when something is ready to read / test. Once this sregistry client is working I'm fairly confident that the CircleCI + Google Build will be a breeze because I don't need to deal with gcloud :P

**Comment by vsoch** [comment]
Hey @wkharold a question for you! I'm looking at the hash of the blob in storage, and comparing with the one under the blob' metadata (e.g., blob.md5_hash) versus the file_hash that is stored alongside the object:

```
# here is the md5_hash for a container
jcd9geF3WYa4nwQhEsXugQ==

# here is the metadata stored separately for the blob, notice that the
{'location': 'gs://sregistry-gcloud-build-vanessa/vanessa-marshmallow-latest.sif#1550349809183214', 'file_hash': [{'file_hash': [{'type': 2, 'value': 'amNkOWdlRjNXWWE0bndRaEVzWHVnUT09'}]}]}
```
They are different! The md5_hash has length (I think I count about 24) and the file_hash has length 32. I tried pulling the container:

```bash
$ sregistry pull vanessa/marshmallow:latest
...
[container][new] vanessa/marshmallow-latest@8dc77d81e1775986b89f042112c5ee81
Success! /home/vanessa/.singularity/shub/vanessa-marshmallow-latest@8dc77d81e1775986b89f042112c5ee81.sif
```
And then taking the md5sum
```bash
$ md5sum /home/vanessa/.singularity/shub/vanessa-marshmallow-latest@8dc77d81e1775986b89f042112c5ee81.sif
8dc77d81e1775986b89f042112c5ee81  /home/vanessa/.singularity/shub/vanessa-marshmallow-latest@8dc77d81e1775986b89f042112c5ee81.sif
```
and sh256sum:
```bash
$ sha256sum /home/vanessa/.singularity/shub/vanessa-marshmallow-latest@8dc77d81e1775986b89f042112c5ee81.sif
7031d69fb424d5c92644d4b6e49c74c65b051ec201299c78ca1f61556da44e93  /home/vanessa/.singularity/shub/vanessa-marshmallow-latest@8dc77d81e1775986b89f042112c5ee81.sif
```
And both return entirely different values! It looks like storage is using [CRC32c](https://cloud.google.com/storage/docs/hashes-etags#CRC32C) which is different than what is expected in a [container manifest](https://docs.docker.com/engine/reference/commandline/images/#list-image-digests) (sha256 is usually preferred). But why is the md5 hash different?

Is there a way to customize the Google Build so that some metadata / environment variables from it are returned in the response? Or to calculate the hash from the blob without downloading it? We would need to do the build, and then somehow get the hash back to the client.

**Comment by vsoch** [comment]
It looks like I can find the secrets in gsutil! That seems to calculate a thing that looks like the Google Storage thing:

```bash
$ gsutil hash /home/vanessa/.singularity/shub/vanessa-marshmallow-latest@8dc77d81e1775986b89f042112c5ee81.sif


Updates are available for some Cloud SDK components.  To install them,
please run:
  $ gcloud components update


WARNING: You have requested checksumming but your crcmod installation isn't
using the module's C extension, so checksumming will run very slowly. For help
installing the extension, please see "gsutil help crcmod".

Hashes [base64] for /home/vanessa/.singularity/shub/vanessa-marshmallow-latest@8dc77d81e1775986b89f042112c5ee81.sif:
	Hash (crc32c):		1+TW2Q==
	Hash (md5):		jcd9geF3WYa4nwQhEsXugQ==

Operation completed over 1 objects/756.0 KiB.                   
```

**Comment by vsoch** [comment]
One more point for discussion! (And don't worry I totally know it's the weekend and don't expect a response soon!)

With the current setup, the builder does a "submit and wait" sort of deal. This is reasonable for small images, but now that I'm testing on CircleCI, I realize that it means the build will be cancelled given waiting for too long. This just happened to me, womp womp:

![image](https://user-images.githubusercontent.com/814322/52905857-4a5c3a80-320e-11e9-96f1-0db26e3f8f10.png)

What I did is to (instead of piping output to file, or the combo of file and stderr/stdout with tee) is add an `--outfile` option so we can print all the output to the console in real time, but then cat the output.txt file to get metadata about the build. This works better, because CircleCI sees a heartbeat!

![image](https://user-images.githubusercontent.com/814322/52905995-3108bd80-3211-11e9-9a78-a0f5af90e2e4.png)

But it has me thinking - one of the benefits of using Google Cloud Build, period, is that we don't need to rely on CircleCI minutes. It actually double taxes us to now be using both CircleCI and Google Cloud Build minutes. So I think I need to rethink this integration - we need more of a webhook sort of thing that has a trigger happen via CircleCI, but then the actual finish doesn't rely on CirceCI still running. Let me know if you have any ideas!

**Comment by vsoch** [comment]
Success! Minus tiny details that we should think about above. I'm like a colorblind species of lizard that turns happy when he sees green :)

![image](https://user-images.githubusercontent.com/814322/52906031-e63b7580-3211-11e9-94a3-a9bb62f30e6a.png)

**Comment by vsoch** [comment]
Just found how to control memory / instance resources -> https://cloud.google.com/cloud-build/docs/api/reference/rest/v1/projects.builds#Build.BuildOptions

I'll wait until someone asks for it before implementing something.

**Comment by vsoch** [comment]
Closing for now, build was added (likely could use some work) but if people aren't using it, it's not important to do.
