### ISSUE TITLE
sregistry, registry client, should honor registry base

### ISSUE THREAD

**Issue by tamasgal** [singularityhub/sregistry-cli#187]
Sorry to bother you again, don't know which communication channel to use ;)

So I set up singularity.km3net.de and now everything works, including the Google Oauth and uploading of images. However, pulling is not working:

```
░ tgal@staticbox:~ py-3.7.2
░ 16:11:40 [I] ✘130 ➜ singularity pull shub://singularity.km3net.de/common/jpp:v11.0.0-rc9
WARNING: Authentication token file not found : Only pulls of public images will succeed
FATAL:   Failed to get manifest from Shub: No response received from singularity hub
```

Although the image is there and it should be public.

**Comment by vsoch** [comment]
I've transferred the issue to the client repository, as this is where the fix will need to be.

**Comment by vsoch** [comment]
hey @tamasgal ! I have a PR ready for you to test here https://github.com/singularityhub/sregistry-cli/pull/188. It should fix the issue with not being able to push / pull when you specify a registry base. See the PDF attached at the top of the PR for additions to the docs (to help guide your testing). To install, you can clone the branch and then install from it.

```bash
pip uninstall sregistry
pip uninstall sregistry
# do that until it tells you it isn't installed

git checkout -b fix/registry-base-required https://www.github.com/singularityhub/sregistry-cli
```
When you've tested and confirmed working, we can merge. Thanks!

**Comment by tamasgal** [comment]
Thank you Vanessa, works like a charm! (and thanks for the subtle reminder to use https haha)

```
░ tgal@staticbox:~ py-3.7.2
░ 16:11:37 [I] ✘1 ➜ SREGISTRY_REGISTRY_NOHTTPS=true sregistry pull registry://singularity.km3net.de/common/jpp:v11.0.0-rc9
[client|registry] [database|sqlite:////home/tgal/.singularity/sregistry.db]
Progress ||----------------------------------|   2.7%
```

**Comment by vsoch** [comment]
ready for merge?

**Comment by vsoch** [comment]
Haha yes, I try to make life harder for the user if he/she makes less secure decisions about registry deployment :P Nothing like having an extra annoying environment variable as a subtle reminder!

**Comment by tamasgal** [comment]
Yes please!

**Comment by tamasgal** [comment]
> Haha yes, I try to make life harder for the user if he/she makes less secure decisions about registry deployment :P Nothing like having an extra annoying environment variable as a subtle reminder!

I totally understand, I manage a whole load of letsencrypt scripts for our collaboration, I just like to set SSL up when everything is working, just for convenience ;)
