### ISSUE TITLE
s3: do not enforce usage of credentials

### ISSUE THREAD

**Issue by tschoonj** [singularityhub/sregistry-cli#204]
**Is your feature request related to a problem? Please describe.**

Currently the S3 backend relies on the use of the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` environment variables to work. This makes sense in a lot of cases, but if you want the s3 bucket to be publicly accessible (especially for pulls, pushes would not be a smart thing to do!), without any authentication/authorization necessary, this doesn't work.

**Describe the solution you'd like**
My proposal is simple: delete the following lines:

https://github.com/singularityhub/sregistry-cli/blob/4e228ec5110de7c8bf2e2f306e80d9c56f3c2e84/sregistry/main/s3/__init__.py#L105-L106
and
https://github.com/singularityhub/sregistry-cli/blob/4e228ec5110de7c8bf2e2f306e80d9c56f3c2e84/sregistry/main/s3/__init__.py#L116-L117

Since `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` if present are [used by boto3](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html#environment-variables) anyway, it won't break any existing code, and it will also work in case no credentials are necessary to access the bucket.

**Describe alternatives you've considered**
Can't think of anything...

**Comment by vsoch** [comment]
Definitely! I'm wondering why we needed to instantiate the client with the variables:

```
        # s3.ServiceResource()
        self.s3 = boto3.resource('s3',
                                 endpoint_url=self.base,
                                 aws_access_key_id=self._id,
                                 aws_secret_access_key=self._key,
                                 config=boto3.session.Config(signature_version=self._signature))
```
I'll push these changes to the debug/s3 branch shortly (the open PR) so you can test.

**Comment by vsoch** [comment]
I don't think the solution is to remove it - it looks like if we specify a config object (which we do) that has a signature, it overrides looking in the environment. The function that is ultimately used is in the botocore here https://github.com/boto/botocore/blob/develop/botocore/session.py#L812.

**Comment by vsoch** [comment]
What we can try is to just not require the setting, so they get passed in as None.

**Comment by vsoch** [comment]
This will be closed by https://github.com/singularityhub/sregistry-cli/pull/202, and @tschoonj if you have a registry it would be handy to test!

**Comment by tschoonj** [comment]
> I don't think the solution is to remove it - it looks like if we specify a config object (which we do) that has a signature, it overrides looking in the environment. The function that is ultimately used is in the botocore here https://github.com/boto/botocore/blob/develop/botocore/session.py#L812.

Hmmm, I don't think that's true... the override only occurs when `if config is not None and config.signature_version is UNSIGNED` is true, but the second part will be false for the values that we pass, given the definition of [UNSIGNED](https://github.com/boto/botocore/blob/260c6c8b44c4d8edd371687d6504bae8f605e1a4/botocore/__init__.py#L68), unless I am mistaken. In this case it goes to: https://github.com/boto/botocore/blob/260c6c8b44c4d8edd371687d6504bae8f605e1a4/botocore/session.py#L826, which uses the environment variables.

**Comment by vsoch** [comment]
Can you give me a public image to test pulling? That would be most straight forward. And then you can test with a private.

**Comment by vsoch** [comment]
Oh I see, so this will be triggered:

https://github.com/boto/botocore/blob/develop/botocore/session.py#L826

Because config is not None, and the signature version is not unsigned. The second loop won't trigger because the pass/id are None, and the third (the missing function) will also return None and be skipped over.  Where is this load_credentials function, it looks in the environment?

**Comment by tschoonj** [comment]
> Can you give me a public image to test pulling? That would be most straight forward. And then you can test with a private.

Give this bucket a try: singularity-sregistry-test

**Comment by tschoonj** [comment]
> Oh I see, so this will be triggered:
> 
> https://github.com/boto/botocore/blob/develop/botocore/session.py#L826
> 
> Because config is not None, and the signature version is not unsigned. The second loop won't trigger because the pass/id are None, and the third (the missing function) will also return None and be skipped over. Where is this load_credentials function, it looks in the environment?

I think it will try a lot of ways to determine the credentials, the [environment](https://github.com/boto/botocore/blob/937d8aee7d9dfcd90801cf7589e85b720e4f4e99/botocore/credentials.py#L872) being one of them.

**Comment by vsoch** [comment]
I got access denied when the envars were set to None.

**Comment by vsoch** [comment]
I think we should merge the current fixes to s3, and address these point by point in other PRs. The current one is getting too large and it's bad practice.

**Comment by tschoonj** [comment]
I agree, many thanks for the work!

**Comment by tschoonj** [comment]
I am going to close this one... this is apparently simply not possible with boto3. [Credentials are apparently always necessary for this to work](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html). And dummy values for AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY don't work :cry: 

Still I think that it should be safe to remove the [aforementioned](https://github.com/singularityhub/sregistry-cli/issues/204#issue-449177513) lines.

Sorry to waste your time like this!

**Comment by vsoch** [comment]
No way, this is how open source works! We discuss, try, and not everything goes through. This is okay :)

**Comment by fenz** [comment]
Hi @vsoch @tschoonj 

I just figured out about this discussion. 
As I wrote here: https://github.com/singularityhub/sregistry-cli/pull/172#issuecomment-452729915, I had an "anonymous pull" working example.
I think this should work in any S3-like storage (so not just Minio but AWS as well).
Let me know if this helps and it is what you wanted to do.

**Comment by vsoch** [comment]
@fenz awesome!

@tschoonj do you want to test it out, and then either of you open a PR to make the changes?

**Comment by tschoonj** [comment]
I can confirm that the following patch works for anonymous pulls: many thanks for the example @fenz!!

@vsoch do you agree with the logic here? Basically we will go into anonymous mode whenever there are no credentials specified...

```diff
diff --git a/sregistry/main/s3/__init__.py b/sregistry/main/s3/__init__.py
index 9b46142..0d603a8 100644
--- a/sregistry/main/s3/__init__.py
+++ b/sregistry/main/s3/__init__.py
@@ -13,6 +13,7 @@ from sregistry.logger import ( RobotNamer, bot )
 from sregistry.main import ApiConnection
 import boto3
 from botocore.client import ClientError
+from botocore import UNSIGNED
 import json
 import os
 
@@ -111,7 +112,7 @@ class Client(ApiConnection):
                                  endpoint_url=self.base,
                                  aws_access_key_id=self._id,
                                  aws_secret_access_key=self._key,
-                                 config=boto3.session.Config(signature_version=self._signature))
+                                 config=boto3.session.Config(signature_version=UNSIGNED if not self._id or not self._key else self._signature))
 
 
     def _update_secrets(self, base=None):
@@ -120,8 +121,8 @@ class Client(ApiConnection):
         '''
         # We are required to have a base, either from environment or terminal
         self.base = self._get_and_update_setting('SREGISTRY_S3_BASE', self.base)
-        self._id = self._required_get_and_update('AWS_ACCESS_KEY_ID')
-        self._key = self._required_get_and_update('AWS_SECRET_ACCESS_KEY')
+        self._id = self._get_and_update_setting('AWS_ACCESS_KEY_ID')
+        self._key = self._get_and_update_setting('AWS_SECRET_ACCESS_KEY')
 
         # Get the desired S3 signature.  Default is the current "s3v4" signature.
         # If specified, user can request "s3" (v2 old) signature

```

**Comment by vsoch** [comment]
I think this could work! My one comment would be that we should give a warning to the user if/when the credentials aren't set (unless boto does this, can you show the output?) If a user is intending to run anonymous, no big deal! But if not, he/she might not be aware of it.

**Comment by tschoonj** [comment]
No warning is currently given if the credentials aren't set: I will add an appropriate message.

**Comment by tschoonj** [comment]
Reopening so I can close it via commit :smile:

**Comment by vsoch** [comment]
@fenz does it look good to you?

**Comment by fenz** [comment]
In my opinion it would be more clear, in case the pull fails because the object is not public, to return to the user an error message instead of a warning.
I don't know the error returned by boto3 but it can possibly be used.

**Comment by tschoonj** [comment]
I checked and in this case, the user gets the warning, followed by an appropriate error that contains the exception message.

I will post the exact text tomorrow morning when I'm back at work.

**Comment by vsoch** [comment]
Thanks @tschoonj and @fenz, I'll keep a look out for updates.
