### ISSUE TITLE
configure: error: Unable to find the libarchive headers, need package libarchive-devel (libarchive-dev on Debian/Ubuntu)

### ISSUE THREAD

**Issue by rpauly** [singularityhub/sregistry-cli#250]
Hi,
When I try to configure the singularity-2.6.1 it gives me an error:
configure: error: Unable to find the libarchive headers, need package libarchive-devel (libarchive-dev on Debian/Ubuntu)
I installed the libarchive-dev and put it in the path, but it is not recognizing it.
suggestions?
Thanks,
Rini

**Comment by vsoch** [comment]
hey @rpauly ! Singularity Registry Client is a wrapper for Singularity, so if you are having issues with installing Singularity proper you should direct them to https://github.com/sylabs/singularity/issue. Maybe it's looking for it on your LD_LIBRARY_PATH and or you might try installing to your system instead? Anyway, the Singularity maintainers can help further - sounds like it's just not finding the library and they can help you debug this.
