### ISSUE TITLE
need to be root to push to a registry?

### ISSUE THREAD

**Issue by victorsndvg** [singularityhub/sregistry-cli#30]
Hi @vsoch ,

I know this tool is under heavy develpmenth right now, but I'm testing it to try to define workflows.

I exported the environment variables to set the right client and secrets and then I tried to push an image to our deployed SRegistry. This action return the following error message: 
```
$ singularity run sregistry-cli push --name mso4sc/sregistry-cli --tag latest sregistry-cli 
[client|registry] [database|sqlite:////home/sandman/.singularity/sregistry.db]
ERROR Return Code 255: b"\x1b[91mERROR  : Singularity is not running with appropriate privileges!\n\x1b[0m\x1b[91mERROR  : Check installation path is not mounted with 'nosuid', and/or consult manual.\n\x1b[0m\x1b[31mABORT  : Retval = 255\n\x1b[0m"
```

Then I did the same as superuser (exporting again the variables) and it worked.

I need to be root to push an image to the registry?

**Comment by vsoch** [comment]
Can you see which singularity is being used to push images? I think we would want the one on your local machine to be used (and not in the container) and you may need to rebuild without Singularity in the container to try that.

Can you test this on an image that isn't the client itself?

After that, I think we would need to look at the command that is causing this issue. I don't see where/why sudo should be needed unless there is a permission that is set (e.g., something sudo owns) that isn't obvious from your copy paste example.

**Comment by victorsndvg** [comment]
Hi @vsoch ,

I'm using Singularity 2.4.2 release in the host. Inside the container the Singularity master branch is used.

I also tried to push a different image with the same result. 

I also try to use the docker container with the same result. Running it in UNprivileged mode i get the following message:

```
$ sregistry push --name mso4sc/example --tag test mso4sc-example-latest.simg 
[client|registry] [database|sqlite:////root/.singularity/sregistry.db]
Singularity: mount-suid (U=0,P=65)> Could not virtualize mount namespace: Operation not permitted

Singularity: mount-suid (U=0,P=65)> Retval = 255

ERROR Return Code 255: b'\x1b[91mERROR  : Could not virtualize mount namespace: Operation not permitted\n\x1b[0m\x1b[31mABORT  : Retval = 255\n\x1b[0m'
```

Now, if I understood well, I have to:
- Build the `sregistry-cli` container without installing Singularity inside the container.

I will report the results as soon as possible.

**Comment by victorsndvg** [comment]
Hi @vsoch ,

I try to not install Singularity within the `sregistry-cli` container, but it seems that it is mandatory. I get the following output:
```
$ singularity run --app registry  sregistry-cli push --name collection/container --tag tag image.simg
WARNING Singularity is not installed, function might be limited.
[client|registry] [database|sqlite:////home/vsande/.singularity/sregistry.db]
ERROR singularity is required for this action [inspect]
```
While having Singularity installed inside the container I was able to somehow "trace " the message error exposed in the first post of this issue:
```
$ singularity run sregistry-cli push --name mso4sc/sregistry-cli --tag latest sregistry-cli 
[client|registry] [database|sqlite:////home/sandman/.singularity/sregistry.db]
ERROR Return Code 255: b"\x1b[91mERROR  : Singularity is not running with appropriate privileges!\n\x1b[0m\x1b[91mERROR  : Check installation path is not mounted with 'nosuid', and/or consult manual.\n\x1b[0m\x1b[31mABORT  : Retval = 255\n\x1b[0m"
```
The trace is:
1. [push.py#L59](https://github.com/singularityhub/sregistry-cli/blob/add/pull-auth/sregistry/main/registry/push.py#L59)
2. [singularity.py#L61](https://github.com/singularityhub/sregistry-cli/blob/add/pull-auth/sregistry/client/singularity.py#L61)
3. [terminal.py#L111](https://github.com/singularityhub/sregistry-cli/blob/add/pull-auth/sregistry/utils/terminal.py#L111)

It is trying to run the following command
```
cmd = ['singularity', '--quiet', 'inspect', '-e', '-d', '-l', '-r', '-hf', '-t', '--json', '/home/vsande/Repos/github/sregistry-cli/mso4sc-sregistry-cli-latest.simg']
```

At the end, it seems that it is trying to run Singularity! (sorry for my ignorance) ... but I think is not possible to run `singularity` from a Singularity container without superuser privileges. I'm right?

Maybe,  has no sense to run `sregistry-cli`  from a singularity container. What do you think?

**Comment by vsoch** [comment]
>> I try to not install Singularity within the `sregistry-cli` container, but it seems that it is mandatory. I get the following output:

Ah yes you do need singularity in the container to use "inspect" to push images (and extract their metadata in the process). The first bug you shared is expected.

Okay, so let's look into the next issue - this looks like a bug! First, here I will export variables to tell the client to use the registry client:

```
SREGISTRY_CLIENT=registry
export SREGISTRY_CLIENT
```

Now trying the command with the sregistry (not inside the container) installed locally:

```
sregistry push --name mso4sc/sregistry-cli --tag latest sregistry-cli
[client|registry] [database|sqlite:////home/vanessa/.singularity/sregistry.db]
[================================] 349/349 MB - 00:00:00
[Return status 201 Created]
```
Works! But now with the container, I reproduce the error

```
singularity run sregistry-cli push --name mso4sc/sregistry-cli --tag latest sregistry-cli
[client|registry] [database|sqlite:////home/vanessa/.singularity/sregistry.db]
ERROR Return Code 255: b"\x1b[91mERROR  : Singularity is not running with appropriate privileges!\n\x1b[0m\x1b[91mERROR  : Check installation path is not mounted with 'nosuid', and/or consult manual.\n\x1b[0m\x1b[31mABORT  : Retval = 255\n\x1b[0m"
```
I stumbled around for a while, and realized that (I think) singularity is working as it should, and it comes down to a path error. Given that you have singularity on the host, it's likely that something from the host is being called from within the container. To test this, I first just tried running `which singularity` from the container, but clearing the host path. And I got... nothing!

```
singularity exec --app registry sregistry-cli which singularity

```
so then I updated the build recipe to add the /usr/local to the path, and we find it:

```
singularity exec --app registry sregistry-cli which singularity
/usr/local/bin/singularity
```
but now we find it with containenv (and are sure we are using the one in the container) but we still get the same error. I don't see any reason that a (non sudo requiring command) should not be possible to do from singularity within a singularity container, but maybe something has changed! I've posted an issue https://github.com/singularityware/singularity/issues/1245 to help get some insight.

**Comment by victorsndvg** [comment]
Yeah, you are right.

I have also check with other versions (master branch, 2.4.2, 2.4.2 and 2.3.2) and all versions have the same bahaviour

**Comment by vsoch** [comment]
okay let's hope that the singularity crew has some insight! I think it's probably an oversight that inspect doesn't need / require any kind of sudo or special permissions, but the command entrypoint is asking for them.

**Comment by DrDaveD** [comment]
@vsoch my understanding is that singularity disallows running any setuid-root program inside of a container, by design, for security reasons.  I did recently demonstrate that one can run unprivileged singularity inside of privileged (setuid-root) singularity.  One more level does not work: you cannot run unprivileged singularity inside of privileged singularity.

One caveat is that I almost always test with --contain --ipc --pid, so it's possible that some of my experience does not apply when you don't use those options.

**Comment by vsoch** [comment]
Interesting - so @victorsnvdg we either need to:

- just use functions inside the container that don't require singularity (not ideal, this severely limits many things)
- stick to using sregistry installed on a host
- expect the user to have singularity installed on the host and use some workaroud to execute the hosts version (and if you are at a computer test what @DrDaveV suggested
- provide a Docker container with a functioning singularity for users that can use docker (important for reproducibility if we can't package everything using singularity, but defeats the purpose if needed to run in userspace on a cluster)

Let me know your thoughts!

**Comment by vsoch** [comment]
hey @victorsndvg ! A quick thought for something to try - how about building the container without singularity, and then binding to your local installation, and making sure it's on the path. Here are snippets that you would want to add to the Singularity build file:

```
%environment
    PATH=/usr/local/bin:$PATH
    export PATH
```
and then remove the bit to install Singularity, and when you run on the host, try:

```
singularity run --bind /usr/local mycontainer.img
```

Actually this might be more helpful for debugging, just a base container (without Singularity) with the above so you can try binding and then issuing commands (that use singularity) to the container:

I called this file `Singularity.error` and build `error.simg` from it.
```
Bootstrap: docker
From: continuumio/miniconda3

# sudo singularity build error.simg Singularity.error

%environment
    PATH=/usr/local/bin:$PATH
    export PATH

%post
    apt-get update && apt-get install -y git build-essential \
                   libtool \
                   squashfs-tools \
                   autotools-dev \
                   automake \
                   autoconf \
                   uuid-dev \
                   libssl-dev

    /opt/conda/bin/pip install dateutils
```

**Comment by victorsndvg** [comment]
HI @vsoch ,

hope everything is going ok for you and your recovery :)

Ok, I agree it could be a solution for debugging purposes. Of course, the better solution is to have it working without doing tricks, but we will see what happen.

Thanks for the workaround!

**Comment by vsoch** [comment]
Let me know if it works when you try it! And I definitely am not in favor of hacks, but this is an issue with singularity itself, and based on https://github.com/singularityware/singularity/issues/1245 it doesn't sound like the software will support "container in a container" sort of deal. So we may be forced to figure out some kind of hack, unfortunately.

**Comment by victorsndvg** [comment]
There aren't an unprivileged stand-alone app to inspect containers? It could be a solution?

Very busy this week. I will test it next week ;)

**Comment by vsoch** [comment]
okay, good luck! The timing works well for me too, I need a bit of catch up time, haha.

The issue doesn't seem to be with running inspect without sudo, it seems like it's an issue with running singularity inside another container, period. But I haven't tested it fully yet! I wanted to give you something to test / work with in the meantime that I'm going from turtle pace back to human pace :)

**Comment by victorsndvg** [comment]
Yeah, 

what I thought is, to run sregistry-cli from a singularity container is not possible because it need singularity installed inside the container. The singularity inside the container is used to inspect images (an maybe something else?). 

Having another tool (valid to be run from a singularity container)   to inspect the images, and using it from sregistry-cli could be a solution?

**Comment by victorsndvg** [comment]
Sorry when I told:
> Very busy this week. I will test it next week ;)

I mean:
Very busy NEXT week. I will test it the following week ;D

**Comment by vsoch** [comment]
haha ok :)

**Comment by victorsndvg** [comment]
Hi @vsoch ,

going back with this issue. I experience the same problem pulling while using sregistry from inside a docker container (running in UNprivileged mode). Again, the error occurs in the call  to `cli.inspect()`.

Replacing the following line make `pull` works in this context:
https://github.com/singularityhub/sregistry-cli/blob/master/sregistry/main/base/inspect.py#L68
by:
`updates = None `

Probably other things are broken with this change ... but why you need to invoke this to pull a container??

Can we live without doing this in `pull`?

Let me know your thoughts!

I simple commented it and it work for pulling images from inside UNprivileged docker container.

**Comment by vsoch** [comment]
Hey @victorsndvg ! We could disable this here, but then the container wouln't have any metadata. Is this inspect command the only issue you are having with running inside Docker? I would expect more, because globally singularity shouldn't work. If it's just this updates issue, then I think it would be reasonable to try and then fall back to not updating the metadata. But if it's a more global issue that needs larger fixing with Singularity overall, it wouldn't make sense to do a try catch when there is the larger issue.

**Comment by victorsndvg** [comment]
Is the only issue when pulling, I've not more info or background for providing strongest conclusions on the side effects of this change. 

I really don't understand why to inspect an image is need for pulling or pushing. Is something related with storing metadata on the client side (pull)? or on the server side (push)?

**Comment by vsoch** [comment]
When you pull an image, we would want to save metadata about it to our database. You are right it's not necessary, it's a "feature" and this is why I suggested a try / catch approach. For clients that it works (outside docker) you get much more rich metadata. For clients where it doesn't, you just skip it.

**Comment by vsoch** [comment]
okay, please try this branch: https://github.com/singularityhub/sregistry-cli/pull/88

**Comment by victorsndvg** [comment]
Hi @vsoch ,

with this patch `singularity` returns error but pull run successfully:

```
# sregistry pull mso4sc/example:latest
[client|registry] [database|sqlite:////root/.singularity/sregistry.db]
Progress |===================================| 100.0% 
Singularity: mount-suid (U=0,P=268)> Could not virtualize file system namespace: Operation not permitted

Singularity: mount-suid (U=0,P=268)> Retval = 255

ERROR Return Code 255: ERROR  : Could not virtualize file system namespace: Operation not permitted
ABORT  : Retval = 255

[container][update] mso4sc/example:latest
Success! /root/.singularity/shub/mso4sc-example:latest.simg
```

replacing https://github.com/singularityhub/sregistry-cli/blob/master/sregistry/main/registry/push.py#L72-L78
with something like:
```
    try:
        if "deffile" in metadata['data']['attributes']:
            if metadata['data']['attributes']['deffile'] is not None:
                fromimage = parse_header(metadata['data']['attributes']['deffile'],
                                         header="from",
                                         remove_header=True) 
                metadata['data']['attributes']['labels']['SREGISTRY_FROM'] = fromimage
                bot.debug("%s was built from a definition file." % image)
    except:
        metadata['data'] = {}
        metadata['data']['attributes'] = {}
        metadata['data']['attributes']['labels'] = {}
        bot.warning("Cannot load metadata")
```

make the `push` work too, at least with the previous version of sregistry ( I don't know what happen with the latest one!)

Output:
```
# sregistry push --name mso4sc/example --tag tmp /root/.singularity/shub/mso4sc-example:latest.simg
[client|registry] [database|sqlite:////root/.singularity/sregistry.db]
Singularity: mount-suid (U=0,P=243)> Could not virtualize file system namespace: Operation not permitted

Singularity: mount-suid (U=0,P=243)> Retval = 255

ERROR Return Code 255: ERROR  : Could not virtualize file system namespace: Operation not permitted
ABORT  : Retval = 255

WARNING Cannot load metadata.
[================================] 88/88 MB - 00:00:00
[Return status 201 Created]
```

**Comment by victorsndvg** [comment]
Is it possible to hide the `singularity` error output and only show the warning?

**Comment by vsoch** [comment]
We could also just skip the metadata entirely - what do you think? I updated the PR to not include metadata, but it would be easy to just delete those sections.

**Comment by vsoch** [comment]
okay please test *the PR above* for these two things. We are still trying to inspect for metadata and it should continue if it fails. You are saying you want this to just go away?

**Comment by victorsndvg** [comment]
Great! everything works perfect!

I was also able to use sregistry from a singularity container. That's what I need!!

Thanks :)
