### ISSUE TITLE
os.rename vs shutil.move

### ISSUE THREAD

**Issue by iliaboti** [singularityhub/sregistry-cli#45]
Hi, 

would it be possible to replace os.rename with shutil.move in /database/sqlite.py -> add()  and everywhere else this is appropriate, since sometimes the paths are in different file systems ?

Thanks,
Ioanins

**Comment by vsoch** [comment]
Definitely! Would you like to submit a PR or I can have a go in the next few days, if it can wait.

**Comment by iliaboti** [comment]
Thanks! I will do the PR as soon as possible.

**Comment by vsoch** [comment]
Awesome Thank you!

**Comment by vsoch** [comment]
This is fixed up. Thanks again!
