### ISSUE TITLE
sregistry pull assumes bootstrap files in /usr/libexec

### ISSUE THREAD

**Issue by slefrancois** [singularityhub/sregistry-cli#46]
The sregistry docker and nvidia clients seem to assume that executable libraries are located in `/usr/libexec`. However, on our Debian 9 systems, they are located in `/usr/lib/x86_64-linux-gnu`:
```
SREGISTRY_CLIENT=nvidia sregistry pull pytorch:17.12
...
Exploding /usr/libexec/singularity/bootstrap-scripts/environment.tar
ERROR b'tar: /usr/libexec/singularity/bootstrap-scripts/environment.tar: Cannot open: No such file or directory\ntar: Error is not recoverable: exiting now\n'
```

The following diff solves the issue on our specific system:
```
--- a/sregistry/main/nvidia/pull.py
+++ b/sregistry/main/nvidia/pull.py
@@ -91,7 +91,7 @@ def pull(self, images, file_name=None, save=True, force=False, **kwargs):
         # Metadata and container guts must come first
         res = which('singularity')['message']
         libexec = res.decode('utf-8').replace('/bin/singularity\n','')
-        envtar = '%s/libexec/singularity/bootstrap-scripts/environment.tar' %libexec
+        envtar = '%s/lib/x86_64-linux-gnu/singularity/bootstrap-scripts/environment.tar' %libexec
         layers = [envtar] + layers
```

**Comment by vsoch** [comment]
Ah so we need to derive the path using another logic other than the Singularity executable. Do you have a suggestion?

**Comment by vsoch** [comment]
could you show me the output of `which singularity` ?

**Comment by slefrancois** [comment]
```
$ which singularity
/usr/bin/singularity
```

`/usr/libexec` is specified in the [Linux FHS](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s07.html) as containing internal application binaries.

However, [Debian's policy](https://www.debian.org/doc/debian-policy/#document-ch-opersys) is to put internal bins in `/usr/lib/triplet`, where triplet is the return of `dpkg-architecture -qDEB_HOST_MULTIARCH`. 

So it's distribution dependant. Maybe there is a standard way to get the system's internal executable   path, but I'm not aware of it myself.

**Comment by vsoch** [comment]
This might be too simple, but given that Singularity has backwards compatibility, the sregistry client could just serve the equivalent environment.tar.

**Comment by vsoch** [comment]
hey @slefrancois one of the developers just had some shell-fu magic, could you try this out and let me know what it returns?

```
dirname $(singularity selftest 2>&1 | grep 'libexec' | awk '{print $4}' | sed -e 's@\(.*/singularity\).*@\1@')
```

**Comment by slefrancois** [comment]
The whole command return null, but I think it's just the `grep 'libexec'` that breaks it since that folder is missing:

```shell
$ singularity selftest 2>&1
 + sh -c test -f /etc/singularity/singularity.conf                                     (retval=0) OK
 + test -u /usr/lib/x86_64-linux-gnu/singularity/bin/action-suid                       (retval=0) OK
 + test -u /usr/lib/x86_64-linux-gnu/singularity/bin/mount-suid                        (retval=0) OK
 + test -u /usr/lib/x86_64-linux-gnu/singularity/bin/start-suid                        (retval=0) OK
$ dirname $(singularity selftest 2>&1 | grep 'lib' | awk '{print $4}' | sed -e 's@\(.*/singularity\).*@\1@')
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu
```

**Comment by vsoch** [comment]
okay have a fix for you! Will submit a PR soon.

**Comment by slefrancois** [comment]
Thanks, will test next week.

**Comment by vsoch** [comment]
Awesome! Thanks @slefrancois and have a fantastic weekend :sun_with_face:
