### ISSUE TITLE
image permission

### ISSUE THREAD

**Issue by iliaboti** [singularityhub/sregistry-cli#53]
Dear @vsoch,

I was wondering what is the default or desired behavior with regards to the images creation permissions. 

In my scenario I would like each user to be able to pull images in a common directory and database set by SREGISTRY_DATABASE.

Then other uses should be able to use those images i.e. with: 

 singularity shell $(sregistry get vsoch/hello-world:latest)

However the images after sregistry pull are created with rw permissions only for the user that has performed the pull.

Is this scenario valid and how can we enable it ? 

Thanks,
Ioannis

**Comment by vsoch** [comment]
This isn't intended use for the sregistry client (to be shared and used by more than one user at once!) The database (sqlite3) only does one read /write well at a time. If you want a shared registry then take a look at the sregistry repository instead!

**Comment by vsoch** [comment]
@iliaboti I see your question is more about permissions. The same rules would apply for a user creating a file. Are you saying you would want the sregistry client to (by default) set the permission of the images to be more permissive? Do you see a situation where the user would want to pull an image and not have it be shared, and under this condition how do you think would be best to determine 1) the client default, and 2) how it's controlled /changed?

**Comment by iliaboti** [comment]
Dear @vsoch, 

what I would like to achieve is have a common directory for downloaded images so that the users do not download the same image on their home directory, thus utilizing more space. I think I understand now  that this can be achieved with "singularity" and SINGULARITY_CACHEDIR env variable.
Having shared pulled images should be the default I guess. 

As for an internal repository, that I was referring to before, sregistry can facilitate the scenario I had in mind. 

Thanks,
Ioannis

**Comment by vsoch** [comment]
yes! The Singularity software itself can control where the cache is if you export `SINGULARITY_CACHEDIR` for all your users. For the internal registry, sregistry (with postgres) can facilitate it for sure, of course installed somewhere that Docker can be. If at some future point we extend the sregistry-cli database to support more than sqlite, it could be a reasonable one too (but not now recommended.) Thanks, and feel free to close if your issue is resolved!

**Comment by iliaboti** [comment]
Thanks a lot for the clarifications! I close the issue.
