### ISSUE TITLE
How to push with sregistry ?

### ISSUE THREAD

**Issue by sysmso** [singularityhub/sregistry-cli#57]
Hello

Sorry but i don't understand how to push a container to a sregistry ? In the doc (https://singularityhub.github.io/sregistry/client.html) it's written to do a sregistry push but the option doesn't seem to be present : 

sregistry push multinest.img --name tools/multinest --tag python
usage: sregistry [-h] [--debug]
                 {version,shell,images,inspect,get,record,add,rm,rmi,search,pull}
                 ...
sregistry: error: argument command: invalid choice: 'push' (choose from 'version', 'shell', 'images', 'inspect', 'get', 'record', 'add', 'rm', 'rmi', 'search', 'pull')

Thanks

**Comment by vsoch** [comment]
The client you choose is entirely based on the environment variable `SREGISTRY_CLIENT` so you should try either of these (and note in the examples the first thing done is to export it, so likely you missed that part). The client that is default is Singularity Hub, which doesn't have a push.

```
SREGISTRY_CLIENT=registry sregistry push multinest.img --name tools/multinest --tag python
```
```
SREGISTRY_CLIENT=registry
export SREGISTRY_CLIENT
sregistry push multinest.img --name tools/multinest --tag python
```

**Comment by sysmso** [comment]
ok sorry i miss the export part, i didn't see that in the docs !
Thanks

**Comment by vsoch** [comment]
No worries! :)
