### ISSUE TITLE
[sregistry login] to set default client and add credential, other

### ISSUE THREAD

**Issue by vsoch** [singularityhub/sregistry-cli#66]
SRegistry login should allow a user to:

1. set a default client to use, and 
2. if there are token / other needed and they aren't in the secrets, the user should be prompted.

**Comment by remyd1** [comment]
Hi @vsoch 

I was thinking about something similar about this, because it is a bit boring to have to edit `.sregistry` file and the run export / echo (to check the actual `SREGISTRY_CLIENT`).

Maybe, a basic `backend` subcommand could take oteher subcommands:
  - info (read `.sregistry` file and display the actual backend),
  - login (what you describe above),
  - switch (to switch between backends described in `.sregistry`,
  - add (to define a new backend in `.sregistry`),
  - rm


Best regards,
Rémy

**Comment by vsoch** [comment]
Login is a good idea! But let's discuss more to figure out how this would work. The backend "adding" happens automatically when the user just uses it, and I don't want to have the user manually adding them (it should be easier than that). 

> info (read .sregistry file and display the actual backend),

All of the backends are also stored in the credential file, so just reading it wouldn't reveal any actual backend.  But if we add an `activate` command this could very easily be shown (see next).

> login (what you describe above),

This could work, but we would need to hold some kind of state. It could be a simple matter of, if the user does:

```
sregistry login globus
```
It would basically set some SREGISTRY_CLIENT variable in the .sregistry file to be `globus` until the user either logs into another, OR does an equivalent logout. I would also say we could do any of the following:

```
sregistry client globus
sregistry activate globus
```
The second is more akin to conda, and both of the above are slightly better than login because they aren't actually logging in, but just specifying to use the client. It also might be the case that we don't log out. Now that I think of it, I think I like these options:

```
sregistry activate globus
sregistry deactivate globus
```
That way we have a way to set `SREGISTRY_CLIENT` (activate), unset it `deactivate` or ignore all together if the user adds a uri to the command, eg

```
sregistry pull nvidia://tensorflow/tensorflow:latest
```
> switch (to switch between backends described in .sregistry,

I don't think we would need switch, the user could just activate another one.

> rm

This would just clear the cached environment variables for a backend. Is this what is desired?

**Comment by remyd1** [comment]
The idea for `rm` was to remove a backend from the `.sregistry` file.

I like the `{de,}activate` keyword to switch between backends but we have to set the default fallback when using `deactivate`: is it the previous state or the official `(s)hub` ?
Then `info` would just display the backend activated.

Rémy.

**Comment by vsoch** [comment]
If the user doesn't specify anything and there is no hint like a uri, the default is Singularity Hub (hub). See here --> https://github.com/singularityhub/sregistry-cli/blob/master/sregistry/main/__init__.py#L63

**Comment by vsoch** [comment]
`rm` is also a command to delete an image, so it would need to be something else!

**Comment by remyd1** [comment]
It was as a second subcommand; eg:
```
sregistry backend rm globus
#or
sregistry backend del globus
```

But if you think we shouln't use `add,

**Comment by vsoch** [comment]
oh I like that idea very much! Yes rm will work in that case. 

I likely won't get to this today (working on something entirely different) but it's on the queue!
