### ISSUE TITLE
Add info message for 403 response when sregistry pull 

### ISSUE THREAD

**Issue by victorsndvg** [singularityhub/sregistry-cli#84]
Hi @vsoch,

Although it works as expected, not authorized pull of a private image doesn't show any message.

In the client side:
```
sregistry pull mso4sc/container:tag
[client|registry] [database|sqlite:////root/.singularity/sregistry.db]
```

In the server side:
```
nginx_1   | 193.144.44.171 - - [02/Mar/2018:07:34:39 +0000] "GET /api/container/mso4sc/container:tag HTTP/1.1" 403 25 "-" "python-requests/2.18.4" "-"
uwsgi_1   | [pid: 49|app: 0|req: 57/57] 193.144.44.171 () {38 vars in 683 bytes} [Fri Mar  2 01:34:39 2018] GET /api/container/mso4sc/container:tag => generated 25 bytes in 91 msecs (HTTP/1.1 403) 5 headers in 164 bytes (1 switches on core 0)
```

I think I'm using the master branch, maybe this is something already solved in another branch ...

Hope It helps!

**Comment by vsoch** [comment]
Hmm yes please use/try the add/permissions branch so we can be on the same page :)

**Comment by victorsndvg** [comment]
Sorry what branch do you mean? there is no `add/permissions` branch in this repo

**Comment by vsoch** [comment]
Apologies I was on my phone and referring to the wrong repo! (the sregistry) and I realize this is for the client.  I just pushed a new branch (of that name) and opened a PR, so you can test with it. I'll link it here in one second...

**Comment by vsoch** [comment]
See https://github.com/singularityhub/sregistry-cli/pull/85 - are there any other issues (either declared on the board or not) you want to address for the client to be paired with the sregistry add/permissions PR?
