### ISSUE TITLE
regex fails on response header for nvidia registry

### ISSUE THREAD

**Issue by niktur** [singularityhub/sregistry-cli#97]
Hi,

we use NVIDIA DGX Cloud service for authentication what can be done either by

```
$ docker login nvcr.io
Username: $oauthtoken
Password: <Your Key>
```
or
```
curl -X POST \
-H "Content-Type: application/json" \
-H "Authorization: APIKey <Your Base64 Encoded Key>" \
https://compute.nvidia.com/api/v1/authenticate
```

Using sregistry to pull images always failed. After digging a bit deeper I found that response header looks like

`challenge= Bearer realm="https://registry.nvidia.com/v2/auth",service="registry.nvidia.com",scope=repository:nvidia/theano:pull`
while regexp expects something like
`challenge= Bearer realm="https://registry.nvidia.com/v2/auth",service="registry.nvidia.com",scope="repository:nvidia/theano:pull"`

Maybe this is site specific but changing of regexp rule in sregistry/main/docker/api.py solves this problem. See below patch
```
--- api.py      2018-03-14 14:20:43.000000000 +0100
+++ api.py.new  2018-03-19 14:39:20.976610303 +0100
@@ -52,7 +52,7 @@
         sys.exit(1)

     challenge = response.headers["Www-Authenticate"]
-    regexp = '^Bearer\s+realm="(.+)",service="(.+)",scope="(.+)",?'
+    regexp = '^Bearer\s+realm="(.+)",service="(.+)",scope=(.+),?'
     match = re.match(regexp, challenge)

     if not match:

```

**Comment by vsoch** [comment]
Ah so the difference here is adding a quote to the end? Could you give me the sregistry version, and the commands exactly you are running to reproduce the error?

**Comment by vsoch** [comment]
And also please confirm you are exporting your NVIDIA credentials to the environment as well, see https://singularityhub.github.io/sregistry-cli/client-nvidia#environment

**Comment by niktur** [comment]
yes, in the quotas around scope match at the end.
```
$ sregistry version
0.0.74
```
`$ MESSAGELEVEL=5 sregistry --debug pull nvidia://nvidia/theano:18.02`

```
$ cat $HOME/.sregistry
{
    "nvidia": {
        "SREGISTRY_NVIDIA_TOKEN": "<here is my APIKye>"
    }
}
```
of course the same behaviour is also with exporting environments.
Registration for NVIDIA DGX Cloud service is there https://compute.nvidia.com/login

**Comment by vsoch** [comment]
Hey @niktur ! The first command still works for me, so I think this must be somehow specific to the endpoint you are getting. Nvidia when the API first came out had some issues with quoting of other variables, so this might be an artifact of that. As a workaround, we can try making both the quotes optional. Could you please try:

```
    challenge = response.headers["Www-Authenticate"]
    regexp = '^Bearer\s+realm="(.+)",service="(.+)",scope="?(.+)"?,?'
    match = re.match(regexp, challenge)
```

and could you please post the actual challenge header you get back from nvidia? I'd like to compare against the one I get back, and reach out to them if needed.

**Comment by niktur** [comment]
Thanx Vanessa, this works. Header looks like:
```
Access-Control-Allow-Headers Authorization, Content-Type
Access-Control-Allow-Methods PUT, HEAD, OPTIONS, GET
Access-Control-Allow-Origin *
Access-Control-Max-Age 21600
Content-Type text/html; charset=utf-8
Date Tue, 20 Mar 2018 15:17:05 GMT
Docker-Distribution-API-Version registry/2.0, registry/2.0
Server nginx/1.13.4
WWW-Authenticate Bearer realm="https://registry.nvidia.com/v2/auth",service="registry.nvidia.com",scope=repository:nvidia/tensorrt:pull
Content-Length 40
Connection keep-alive
```
for
`MESSAGELEVEL=5 sregistry --debug pull nvidia://nvidia/tensorrt:18.02-py2`

**Comment by vsoch** [comment]
hey @niktur one more question! What version of python and requests are you using?

**Comment by vsoch** [comment]
Okay, so I've tested both ways. When I do the fix for the regexp above, it breaks docker for me (does it still work for you?) Just try:

```
sregistry pull docker://ubuntu:14.04 
```
The above stops working when I add the optional ? as above.

I think this is an issue that would be best fixed from the nvidia endpoint - that thing I think should be in quotes.  I'll reach out to them and see what I can do.

**Comment by vsoch** [comment]
okay, we have an answer! This is a known issue. Specifically, read here --> https://github.com/singularityware/singularity/issues/1159#issuecomment-347342220

>> That is returned by a legacy system and we cannot change it. Also, (you are correct) it returns scopes without quotes. If any user experiences this issue, we suggest they migrate to NGC.

It would be unwise for sregistry to make this change, please see the specification above!

**Comment by niktur** [comment]
Hi Vanessa. ok I see this is site specific as I thought in the beginning. But docker actually can deal with quoted and unquoted headers. I have just simply modified scope match and it works for nvidia as well as for docker: 
`regexp= ^Bearer\s+realm="(.+)",service="(.+)",scope="?([^",]+)"?,?`
